---
apiVersion: verify.gov.uk/v1beta1
kind: CertificateRequest
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: eidas-pki
  name: verify-root-ca-test-a1
  namespace: {{ .Release.Namespace }}
spec:
  countryCode: GB
  commonName: GOV.UK Verify Test Root CA A1
  expiryMonths: 120
  organization: Cabinet Office
  organizationUnit: GDS
  location: London
  CACert: true
